export const CREATE_CARD = 'CREATE_CARD'
export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_GRAPH = 'FETCH_DATA_GRAPH'
export const DEL_CARD = 'DEL_CARD'
export const IS_LOADING = 'IS_LOADING'